import { Asset } from 'expo-asset';
import { ImageSourcePropType } from 'react-native';

export const images: { [key: string]: ImageSourcePropType } = {
  logo: require('@/assets/images/logo.png'),
  logo_blue: require('@/assets/images/logo_blue.png'),
  background: require('@/assets/images/background.png'),
  arrow_back: require('@/assets/images/arrow_back_ios.png'),
  arrow_blue: require('@/assets/images/arrow_blue_ios.png'),
  hand: require('@/assets/images/hand.png'),
  star: require('@/assets/images/star.png'),
  emoji_stars: require('@/assets/images/emoji_stars.png'),
  money: require('@/assets/images/money.png'),
  bags: require('@/assets/images/bags.png'),
  help: require('@/assets/images/help.png'),
  profile_default: require('@/assets/images/profile_default.png'),
  banner: require('@/assets/images/banner.png'),
  banner_two: require('@/assets/images/banner_2.png'),
  google_button: require('@/assets/images/google_button.png'),
  icon_gold: require('@/assets/images/gold.png'),
  arrow_back_white: require('@/assets/images/arrow_back_ios_white.png'),
  arrow_back_blue: require('@/assets/images/arrow_back_ios_blue.png'),
  profile_white: require('@/assets/images/profile_white.png'),
  security_white: require('@/assets/images/security_white.png'),
  doubt_white: require('@/assets/images/doubt_white.png'),
  logout_blue: require('@/assets/images/logout_blue.png'),
  logo_featured: require('@/assets/images/logo_featured.png'),
  logo_phone: require('@/assets/images/logo_phone.png'),
  logo_electro: require('@/assets/images/logo_electro.png'),
  filter: require('@/assets/images/filter.png'),
  samsumg: require('@/assets/images/image_frame.png'),
  money_white: require('@/assets/images/money_white.png'),
  platinum: require('@/assets/images/platino.png'),
  info: require('@/assets/images/info.png'),
  location_liniers: require('@/assets/images/location_1.png'),
  location_avellaneda: require('@/assets/images/location_2.png'),
  pay_1: require('@/assets/images/pay_1.png'),
  pay_2: require('@/assets/images/pay_2.png'),
  pay_3: require('@/assets/images/pay_3.png'),
  pay_4: require('@/assets/images/pay_4.png'),
  image_benefits: require('@/assets/images/image_benefits.png'),
  image_benefits_1: require('@/assets/images/image_benefits_1.png'),
  image_benefits_2: require('@/assets/images/image_benefits_2.png'),
  image_trips: require('@/assets/images/image_trips.png'),
  contact_1: require('@/assets/images/contact_1.png'),
  contact_2: require('@/assets/images/contact_2.png'),
  contact_3: require('@/assets/images/contact_3.png'),
  logo_purple: require('@/assets/images/logo_purple.png'),
  whatsapp: require('@/assets/images/whatsapp.png'),
  google_maps: require('@/assets/images/google_maps.png'),
  home_icon_blue: require('@/assets/images/home_icon_blue.png'),
  home_icon_grey: require('@/assets/images/home_icon_grey.png'),
  benefits_icon_grey: require('@/assets/images/benefits_icon_grey.png'),
  benefits_icon_blue: require('@/assets/images/benefits_icon_blue.png'),
  logo_icon_white: require('@/assets/images/logo_icon_white.png'),
  shop_icon_red: require('@/assets/images/shop_icon_red.png'),
  shop_icon_grey: require('@/assets/images/shop_icon_grey.png'),
  profile_icon_blue: require('@/assets/images/profile_icon_blue.png'),
  profile_icon_grey: require('@/assets/images/profile_icon_grey.png'),
  breaking_news_white: require('@/assets/images/breaking_news_white.png'),
  notification_white: require('@/assets/images/notification_white.png'),
  check_blue: require('@/assets/images/check_blue.png'),
  mood: require('@/assets/images/mood.png'),
  mood_bad: require('@/assets/images/mood_bad.png'),
  sentiment_sad: require('@/assets/images/sentiment_sad.png'),
  help_icon: require('@/assets/images/help_icon.png'),
  arrow_back_icon: require('@/assets/images/arrow_back_icon.png'),
  arrow_bottom_blue: require('@/assets/images/arrow_bottom_blue.png'),
  arrow_top_blue: require('@/assets/images/arrow_top_blue.png'),
  edit_square_blue: require('@/assets/images/edit_square_blue.png'),
  key_vertical_blue: require('@/assets/images/key_vertical_blue.png'),
  enhanced_encryption_blue: require('@/assets/images/enhanced_encryption_blue.png'),
  shield_blue: require('@/assets/images/shield_blue.png'),
  for_you_blue: require('@/assets/images/for_you_blue.png'),
  id_card_blue: require('@/assets/images/id_card_blue.png'),
  cake_blue: require('@/assets/images/cake_blue.png'),
  dock_blue: require('@/assets/images/dock_blue.png'),
  mail_blue: require('@/assets/images/mail_blue.png'),
  shopping: require('@/assets/images/shopping.png'),
  local_pizza: require('@/assets/images/local_pizza.png'),
  apparel: require('@/assets/images/apparel.png'),
  school: require('@/assets/images/school.png'),
  image_recom: require('@/assets/images/image_recom.png'),
  world: require('@/assets/images/world.png'),
  image_qr: require('@/assets/images/image_qr.png'),
  image_completed: require('@/assets/images/image_completed.png'),
  cuponizate_white: require('@/assets/images/cuponizate_white.png'),
  hamburguer_menu: require('@/assets/images/hamburguer_menu.png'),
  magnifying_glass: require('@/assets/images/magnifying_glass.png'),
  // Mockups
  mockup_1: require('@/assets/mockups/01.png'),
  mockup_2: require('@/assets/mockups/02.png'),
  mockup_3: require('@/assets/mockups/03.png'),
  mockup_4: require('@/assets/mockups/04.png'),
  mockup_5: require('@/assets/mockups/05.png'),
};

type VirtualAssetModuleType = number | string;

// preload images
const imageAssets = Object.keys(images).map(key => {
  return Asset.fromModule(images[key] as VirtualAssetModuleType).downloadAsync();
});

export const loadImages = () => Promise.all(imageAssets);
